export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";

export const DOWNLOAD_PRODUCTS = "DOWNLOAD_PRODUCTS";
export const DOWNLOAD_PRODUCTS_SUCCESS = "DOWNLOAD_PRODUCTS_SUCCESS";
export const DOWNLOAD_PRODUCTS_ERROR = "DOWNLOAD_PRODUCTS_ERROR";

export const DELETE_PRODUCTS = "DELETE_PRODUCTS";
export const DELETE_PRODUCTS_SUCCESS = "DELETE_PRODUCTS_SUCCESS";
export const DELETE_PRODUCTS_ERROR = "DELETE_PRODUCTS_ERROR";

export const EDIT_PRODUCTS = "EDIT_PRODUCTS";
export const START_EDIT_PRODUCTS = "START_EDIT_PRODUCTS";
export const EDIT_PRODUCTS_SUCCESS = "EDIT_PRODUCTS_SUCCESS";
export const EDIT_PRODUCTS_ERROR = "EDIT_PRODUCTS_ERROR";

export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";

